name: sprint pre-merge check

on: 
  push:
    branches:
    - features/sprint*
  pull_request:
    branches:
    - features/sprint*

env:
  CMAKE_VERSION: 3.17.2

jobs:
  cmake-build:
    name: cmake build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        dotnet: [3.1.200]

    steps:
    - name: setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - uses: actions/checkout@v2
    - name: build and test on ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        ./tools/build.sh
        ./tools/test.sh
    - name: build and test on mac
      if: matrix.os == 'macos-latest'
      run: |
        ./tools/build.sh
        ./tools/test.sh
    - name: build and test on windows
      if: matrix.os == 'windows-latest'
      run: |
        .\tools\build.bat
        .\tools\test.bat
