name: pre-merge check

on: 
  push:
    branches:
    - master
    - develop
    - features/sprint*
  pull_request:
    branches:
    - master
    - develop
    - features/sprint*

jobs:
  test-dotnet5:
    name: dotnet 5.0
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
#        os: [macos-10.15, macos-11.0, windows-2019, ubuntu-20.04, ubuntu-18.04]
        os: [macos-10.15, windows-2019, ubuntu-20.04, ubuntu-18.04]

    steps:
    - name: setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - uses: actions/checkout@v2
    - name: build and test
      if: runner.os != 'Windows'
      run: |
        ./tools/build.sh
        ./tools/test.sh
    - name: build and test on win
      if: runner.os == 'Windows'
      run: |
        ./tools/build.bat
        ./tools/test.bat

  test-dotnet3:
    name: dotnet 3.1
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, windows-2019, ubuntu-20.04, ubuntu-18.04]

    steps:
    - name: setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - uses: actions/checkout@v2
    - name: build and test
      if: runner.os != 'Windows'
      run: |
        ./tools/build_core3.sh
        ./tools/test_core3.sh
    - name: build and test on win
      if: runner.os == 'Windows'
      run: |
        ./tools/build_core3.bat
        ./tools/test_core3.bat
