name: create-release-upload

on: 
  push:
    tags:
    - 'v*'

env:
  CMAKE_VERSION: 3.17.2
  XCODE_VERSION: 11.5
  DOTNET_VERSION: 3.1.200

jobs:
  create-releases:
    name: create-releases
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Changes in this Release
          - First Change
          - Second Change
        draft: false
        prerelease: false
#      continue-on-error: true
    - name: write upload url
      env:
        url: ${{ steps.create_release.outputs.upload_url }}
      run: |
        echo $url > upload_url.txt
    - name: upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: artifact-upload_url
        path: upload_url.txt

  upload-object-windows-mingw:
    name: upload-object-win-mingw
    needs: create-releases
    runs-on: windows-latest

    steps:
    - name: setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: checkout
      uses: actions/checkout@v2
    - name: download artifact
      uses: actions/download-artifact@v1
      with:
        name: artifact-upload_url
    - name: dump upload url
      id: get_url
      run: |
        export up_url="$(cat artifact-upload_url/upload_url.txt)"
        echo "::set-output name=upload_url::$up_url"
        echo "url=$up_url"
      shell: bash
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      shell: bash
    - name: dump version
      env:
        version: ${{ steps.get_version.outputs.VERSION }}
      run: echo "version=${version}"
      shell: bash
    - name: cmake-build
      run: |
        .\tools\build.bat
        .\tools\test.bat
      timeout-minutes: 20
    - name: cmake-install
      shell: cmd
      run: |
        mkdir dist
        COPY /Y /B dotnet_project\CfdCsharpProject\bin\Release\netstandard2.1\cfdcs.* dist
        COPY /Y /B build\Release\* dist
    - name: create archive file
      run: |
        cd dist
        del gen_context.exe
        Compress-Archive -Path ./* -DestinationPath ../cfd.zip
        cd ..
        echo "---- dump zip file ----"
        dir .
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_url.outputs.upload_url }}
        asset_path: ./cfd.zip
        asset_name: cfdcs-${{ steps.get_version.outputs.VERSION }}-win-dotnet${{env.DOTNET_VERSION}}-msvc2019-x86_64.zip
        asset_content_type: application/zip

  upload-object-ubuntu:
    name: upload-object-ubuntu
    needs: create-releases
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]

    steps:
    - name: setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: checkout
      uses: actions/checkout@v1
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: cmake-useCache-ubuntu
      uses: actions/cache@v1
      id: cache
      with:
        path: cache/cmake
        key: ${{ runner.os }}-cmake-${{ env.CMAKE_VERSION }}-x64-0
        restore-keys: |
          ${{ runner.os }}-cmake-${{ env.CMAKE_VERSION }}-x64-
    - name: cmake-download-ubuntu
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        mkdir -p cache/cmake
        cd cache/cmake
        wget https://github.com/Kitware/CMake/releases/download/v$CMAKE_VERSION/cmake-$CMAKE_VERSION-Linux-x86_64.tar.gz
        cd ../..
    - name: cmake-setting-ubuntu
      run: |
        export cmake_file_name="cmake-$CMAKE_VERSION-Linux-x86_64"
        cd cache/cmake
        tar zxvf $cmake_file_name.tar.gz
        chmod +x $cmake_file_name/bin/cmake $cmake_file_name/bin/ctest
        export CURRENT_DIR=$(pwd)
        echo ::add-path::$CURRENT_DIR/$cmake_file_name/bin
        cd ../..
    - name: cmake-build
      run: |
        ./tools/build.sh
    - name: test
      run: |
        ./tools/test.sh
    - name: create archive file
      run: |
        mkdir dist
        cp -rp build/Release/* dist
        cp -rp dotnet_project/CfdCsharpProject/bin/Release/netstandard2.1/cfdcs.* dist
        cd dist
        zip -r cfd.zip .
        echo "---- dump zip file ----"
        ls -l
    - name: download artifact
      uses: actions/download-artifact@v1
      with:
        name: artifact-upload_url
    - name: dump upload url
      id: get_url
      run: |
        url=$(cat artifact-upload_url/upload_url.txt)
        echo ::set-output name=upload_url::$url
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_url.outputs.upload_url }}
        asset_path: ./dist/cfd.zip
        asset_name: cfdcs-${{ steps.get_version.outputs.VERSION }}-${{ matrix.os }}-dotnet${{env.DOTNET_VERSION}}-gcc-x86_64.zip
        asset_content_type: application/zip
    - name: ubuntu-after
      run: rm -rf cache/cmake/cmake-$CMAKE_VERSION-Linux-x86_64

  upload-object-macos:
    name: upload-object-macos
    needs: create-releases
    runs-on: macos-latest

    steps:
    - name: setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: checkout
      uses: actions/checkout@v1
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_${{env.XCODE_VERSION}}.app/Contents/Developer'
    - name: Show Xcode version
      run: xcodebuild -version
    - name: cmake-build
      run: |
        ./tools/build.sh
    - name: test
      run: |
        ./tools/test.sh
    - name: create archive file
      run: |
        mkdir dist
        cp -rp build/Release/* dist
        cp -rp dotnet_project/CfdCsharpProject/bin/Release/netstandard2.1/cfdcs.* dist
        cd dist
        zip -r cfd.zip .
        echo "---- dump zip file ----"
        ls -l
    - name: download artifact
      uses: actions/download-artifact@v1
      with:
        name: artifact-upload_url
    - name: dump upload url
      id: get_url
      run: |
        url=$(cat artifact-upload_url/upload_url.txt)
        echo ::set-output name=upload_url::$url
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_url.outputs.upload_url }}
        asset_path: ./dist/cfd.zip
        asset_name: cfdcs-${{ steps.get_version.outputs.VERSION }}-macos-dotnet${{env.DOTNET_VERSION}}-xcode${{env.XCODE_VERSION}}-gcc-x86_64.zip
        asset_content_type: application/zip

